# Generated by Django 5.0.6 on 2024-07-17 19:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
